<?php
// $Id: dumper.install,v 1.3.2.2 2009/11/04 12:07:32 franz Exp $

/**
 * @file Dumper Module Installation file
 */

/**
 * Implementation of hook_install().
 */
function dumper_install() {
  
}


/**
 * Implementation of hook_uninstall().
 * @todo list all variables
 */
function dumper_uninstall() {

  variable_del('dumper_extra_options');
  variable_del('dumper_exclude_users');
  variable_del('dumper_exclude_cache');
}
